services:
  postgres:
    image: postgres:17
    container_name: postgres_demo
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    container_name: maildev_demo
    ports:
      - "1080:1080"
      - "1025:1025"

  smppsim:
    build: ./smppsim
    container_name: smppsim_demo
    ports:
      - "2775:2775"
      - "8989:8989"

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock_demo
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  postgres_data:
